export const CONTACT_FORM_LIMITS = {
  FIRST_NAME_MIN: 2,
  FIRST_NAME_MAX: 50,
  LAST_NAME_MIN: 2,
  LAST_NAME_MAX: 50,
  COMPANY_MAX: 100,
  PHONE_MAX: 20,
  MESSAGE_MIN: 10,
  MESSAGE_MAX: 1000,
} as const;
