export {
  PROPERTY_CTA_CLASS as SHOWCASE_CTA_CLASS,
  PROPERTY_CTA_SECONDARY_CLASS as SHOWCASE_CTA_SECONDARY_CLASS,
  PROPERTY_CTA_COMPACT_BASE as SHOWCASE_CTA_COMPACT_BASE,
  PROPERTY_CTA_COMPACT_CLASS as SHOWCASE_CTA_COMPACT_CLASS,
  PROPERTY_CTA_COMPACT_GROUP_CLASS as SHOWCASE_CTA_COMPACT_GROUP_CLASS,
} from "./property-cta";
