

import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/context/ThemeContext";
import CompanyTitle from "@/components/branding/companyTitle/CompanyTitle";
import Script from "next/script";
import Topmenu from "@/components/layout/top-menu/TopMenu";
import Footer from "@/components/layout/footer/Footer";
import SecondaryNav from "@/components/layout/secondary-nav/SecondaryNav";
import CategoryNav from "@/components/layout/category-nav/CategoryNav";


const roboto = Roboto({ subsets: ["latin"], weight: ["300", "400", "500", "700"], display: "swap" });

export const metadata: Metadata = {
  title: "Rumpke Immobilien",
  description: "Generated by Rumpke Immobilien",
};

type RootLayoutProps = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en" className={roboto.className} suppressHydrationWarning>
      <body className="antialiased">
        <Script src="https://widget.cloudinary.com/v2.0/global/all.js" strategy="beforeInteractive" />
        <ThemeProvider>
          <div className="bg-bg-l text-zinc-800 dark:bg-bg-d dark:text-zinc-100">
            {/* <div className='fixed top-0 left-50 hidden md:flex w-fit mx-auto items-center py-2 px-3  rounded-tr-md gap-5 bg-primary dark:bg-primary-dark text-white z-500'>
              <ContactButtom />
            </div> */}
            <div className="">
              <Topmenu />
              <div style={{ paddingTop: 'var(--topbar-height)' }}>
                <CategoryNav />
                {children}
              </div>
              <Footer />
              <SecondaryNav />
            </div>
          </div>
          <CompanyTitle />
        </ThemeProvider>
      </body>
    </html>
  );
}
