

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/context/ThemeContext";
import CompanyTitle from "@/components/branding/companyTitle/CompanyTitle";
import Script from "next/script";

import ContactButtom from '@/components/features/contact-buttom/ContactTooltip';
import Topmenu from "@/components/layout/top-menu/TopMenu";
import Footer from "@/components/layout/footer/Footer";
import SecondaryNav from "@/components/layout/secondary-nav/SecondaryNav";




const inter = Inter({ subsets: ["latin"], display: "swap" });

export const metadata: Metadata = {
  title: "Rumpke Immobilien",
  description: "Generated by Rumpke Immobilien",
};

type RootLayoutProps = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en" className={inter.className}>
      <body className="antialiased">
        <Script src="https://widget.cloudinary.com/v2.0/global/all.js" strategy="beforeInteractive" />
        <ThemeProvider>
          <div className="bg-bg-l text-zinc-800 dark:bg-bg-d dark:text-zinc-100">
            {/* <div className='hidden md:block fixed bottom-0 left-6 xl:right-36 z-500'>
              <ContactButtom />
            </div> */}
            <div className="">
              <Topmenu />
              <div style={{ paddingTop: 'var(--topbar-height)' }}>
                {children}
              </div>
              <Footer />
              <SecondaryNav />
            </div>
          </div>
          <CompanyTitle />
        </ThemeProvider>
      </body>
    </html>
  );
}
